// <auto-generated />
namespace Kabylia.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DisplayRouteOnMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisplayRouteOnMap));
        
        string IMigrationMetadata.Id
        {
            get { return "202101060450090_DisplayRouteOnMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
